### ISSUE TITLE
NPM organization name for launchpack trademark violation

### ISSUE THREAD

**Issue by Launchpack** [do4ng/do4ng.github.io#2]
Hello, we are Launchpack Inc. in Korea, the software company. At first we apologize about no related repository issue.
We found that the organization named 'launchpack' in npmjs.com is related with you. The username is 'kangdongmandoo'.
There are [@launchpack/cli](https://www.npmjs.com/package/@launchpack/cli),
[@launchpack/esbuild](https://www.npmjs.com/package/@launchpack/esbuild) and [@launchpack/import](https://www.npmjs.com/package/@launchpack/import) packages in npm. "Launchpack" is our company name and our trademark. We don't know why you choose this organization name, however the organization name is required for our further development. Sorry about the word 'voilation' in the title. We couldn't find any contact for you.
If this is just an accident, we request the name back to our team. We really need this name. Thank you.

It seems you can speak Korean, below is the Korean version of this issue.

안녕하세요, 저희는 소프트웨어 개발사인 한국의 런치팩 주식회사 입니다. 먼저 관련없는 저장소에 이슈를 등록하게 되어 사과의 말씀을 드립니다.
저희는 npmjs.com 에 'launchpack' 조직 이름이 당신과 연관이 있는 것을 발견했습니다. 사용자 이름은 'kangdongmandoo' 입니다.
그곳에는 세 개의 '@launchpack/' 으로 시작하는 패키지가 있습니다. "Launchpack (런치팩)"은 저희의 회사 이름이자 상표권 입니다. 저희는 왜 당신이 이 이름을 선택했는지 알지 못합니다. 하지만 해당 조직 이름은 저희의 추후 개발에 요구됩니다. "침해" 라는 단어의 선택에는 죄송합니다. 저희는 당신에 대한 아무런 연락처도 찾지 못하였습니다. 자극적인 제목을 사용한 것에 사과드립니다.
만약 이것이 우연일 뿐이라면, 저희는 해당 조직 이름을 저희 팀에 되돌려 주기를 요구합니다. 저희는 정말 그 이름이 필요합니다. 감사합니다.

당신이 한국어를 할 수 있는 것 같고, 저희도 그러하기 때문에 한국어 번역을 첨부합니다.

**Comment by do4ng** [comment]
답장이 늦어서 죄송합니다 취미로 하는 것이기 때문에 그 당시 아무런 의도없이 이름을 지었습니다. 혹시 그냥 조직을 지우면 되나요? 제가 어떤식으로 도울 수 있나요?

**Comment by Launchpack** [comment]
Thank you for the response. And also thanks for your help.
You can transfer the organization permission to our teammate, Aspen (https://www.npmjs.com/~aspschn).
If you can't believe that account, contact first to support@launchpack.co.kr
Thank you again, and sorry for the not related issue.

답변 감사합니다. 그리고 도움을 주신다니 또한 감사합니다.
먼저 저희 팀원인 Aspen(https://www.npmjs.com/~aspschn) 에게 조직의 권한을 넘겨주실 수 있습니다.
만약 이 계정을 믿지 못하시겠다면 우선 support@launchpack.co.kr 로 연락 주셔도 됩니다.
다시 한 번 감사드리며, 연관 없는 이슈를 등록해 죄송합니다.
